### ISSUE TITLE
Resume Training

### ISSUE THREAD

**Issue by macriluke** [Hamza5/Pipeline-diacritizer#3]
Does this have the ability to resume training if it was interrupted partway through?

**Comment by Hamza5** [comment]
Yes, it does. Although, if the training was stopped before the end of the iteration, you will lose the progress of that iteration. Saving the parameters happens at the end of every iteration.

**Comment by macriluke** [comment]
So I just have to run training and point --weights-dir to the directory with the weights files? I don't see any --resume flag.

**Comment by Hamza5** [comment]
Yes exactly. The script looks for the existing weight files and load them automatically before starting the training.
